# localization fix for OS X
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
eval `/usr/libexec/path_helper -s`
add_pipenv_to_kernels () {
   venv_name=$(basename -- $(pipenv --venv))
   venv_prettyname=$(echo $venv_name | cut -d '-' -f 1)
   echo "Adding ipython kernel to list of jupyter kernels"
    $(pipenv --py) -m ipykernel install --user --name $venv_name --display-name "Python3 ($venv_prettyname)"
}

init_python3_pipenv () {
   echo "Estting up pipenv environment"
   pipenv install --three
   echo "Installing ipython kernel"
   pipenv install --dev ipykernel
   add_pipenv_to_kernels
}

