if [ "$(arch)" = "arm64" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    eval "$(/usr/local/bin/brew shellenv)"
fi
eval "$(pyenv init -)"
path=("$HOME/.local/bin" $path)  # user pip
path=("$HOME/.poetry/bin" $path)  # poetry
path=("$HOME/.cargo/bin" $path)  # Cargo
path=("$HOME/bin" $path)  # Custom binaries

export PATH
# Locale settings
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export ZK_NOTEBOOK_DIR="$HOME/Notes"
export VISUAL=nvim
export EDITOR=$VISUAL
