eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(pyenv init -)"
path=("$HOME/.local/bin" $path)  # user pip
path=("$HOME/.poetry/bin" $path)  # poetry

export PATH
# Locale settings
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export ZK_NOTEBOOK_DIR="$HOME/Notes"
export VISUAL=nvim
export EDITOR=$VISUAL
eval "$(pyenv init --path)"
