zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename $HOME'/.zshrc'

autoload -Uz compinit
compinit

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
unsetopt beep
bindkey -e

export EDITOR=nvim
export CLICOLOR=yes

set-window-title() {
  window_title="\e]0;${${PWD/#"$HOME"/~}}\a"
  echo -ne "$window_title"
}

autoload -Uz add-zsh-hook

set-window-title
add-zsh-hook precmd set-window-title

PROMPT='%F{blue}%B%~%b%f %F{green}%#%f '
export GPG_TTY=$(tty)

alias vim=nvim
alias nvim-kickstart='NVIM_APPNAME="nvim-kickstart" nvim'
alias ask="ollama run mistral"
alias ask_code="ollama run codellama"

function proj () {
    # Goto project.
    cd $(find ~/Projects -maxdepth 1 -type d | fzy)
}

function goto () {
    cd ~/$(cat ~/.dotfiles/common_paths.txt | fzy)
}

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mh669599/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mh669599/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mh669599/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mh669599/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
