zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename $HOME'/.zshrc'

autoload -Uz compinit
compinit

source <(fzf --zsh)

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
unsetopt beep
bindkey -e

export EDITOR=nvim
export CLICOLOR=yes

set-window-title() {
  window_title="\e]0;${${PWD/#"$HOME"/~}}\a"
  echo -ne "$window_title"
}

autoload -Uz add-zsh-hook

set-window-title
add-zsh-hook precmd set-window-title

PROMPT='%F{blue}%B%~%b%f %F{green}%#%f '
export GPG_TTY=$(tty)

alias vim=nvim

function proj () {
    # Goto project.
    cd $(find ~/Projects -maxdepth 1 -type d | fzy)
}

function goto () {
    cd ~/$(cat ~/.dotfiles/common_paths.txt | fzy)
}
. "$HOME/.cargo/env"
