require("expectationmax.remap")
require("expectationmax.lazy")
require("expectationmax.environment")
require("expectationmax.settings")
require("expectationmax.netrw")
-- require("expectationmax.packer")
require("expectationmax.filetypes")
